server:
  port: 8082

spring:
  application:
    name: software_takeout
  datasource:
    url: jdbc:mysql://localhost:3306/andexam?useUnicode=true&characterEncoding=utf8
    username: root
    password: ...
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: ...
    host: ...

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启mp运行日志
    map-underscore-to-camel-case: false # 驼峰映射
  mapper-locations: classpath:/mapper/*.xml
